import { test, expect, type Page } from '@playwright/test';
import { clearDatabase, createIdentityAndUnlock, navigateViaHarness } from './fixtures';
import { privateRelays } from './helpers/private-relays';
async function confirmPin(page: Page) {
  for (const digit of '123456') await page.getByRole('button', { name: digit, exact: true }).click();
}
test('creates persona-owned bots and gates standalone key export behind fresh authentication', async ({ page, context }) => {
  const relays = privateRelays();
  await relays.install(context);
  await clearDatabase(page); await createIdentityAndUnlock(page);
  await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true,
    value: { writeText: async (text: string) => { (window as unknown as { copied: string }).copied = text; } } }));
  await navigateViaHarness(page, 'settings');
  await page.getByRole('button', { name: /Bots.*Keys and persona ownership/ }).click();
  await expect(page.getByLabel('Owner persona')).toHaveValue(/^[0-9a-f]{64}$/);
  await page.getByLabel('Bot name').fill('Helper');
  await page.getByRole('button', { name: 'Create bot', exact: true }).click();
  await confirmPin(page);
  await expect(page.getByRole('heading', { name: 'Helper · Bot', exact: true })).toBeVisible();
  await expect(page.getByText('Recovery-derived · bot-0')).toBeVisible();
  const helper = page.locator('section.card').filter({ has: page.getByRole('heading', { name: 'Helper · Bot', exact: true }) });
  await helper.getByRole('button', { name: 'Create private ownership link' }).click();
  await confirmPin(page);
  await expect(helper.getByText('Ownership private', { exact: true })).toBeVisible();
  expect([...relays.events.values()].filter(event => event.tags.some(t => t[0] === 'type' && t[1] === 'bot-ownership'))).toHaveLength(0);
  await helper.getByRole('button', { name: 'Publish ownership', exact: true }).click();
  await helper.getByRole('button', { name: 'Confirm publication' }).click();
  await confirmPin(page);
  await expect(helper.getByText('Ownership published', { exact: true })).toBeVisible();
  expect([...relays.events.values()].filter(event => event.tags.some(t => t[0] === 'type' && t[1] === 'bot-ownership'))).toHaveLength(1);
  await helper.getByRole('button', { name: 'Revoke ownership' }).click();
  await confirmPin(page);
  await expect(helper.getByText('Ownership revoked', { exact: true })).toBeVisible();
  await expect.poll(() => [...relays.events.values()].some(event => event.tags.some(t => t[0] === 'type' && t[1] === 'bot-ownership')
    && event.tags.some(t => t[0] === 'status' && t[1] === 'revoked'))).toBe(true);
  await page.getByLabel('Bot name').fill('Game Helper');
  await page.getByLabel('Bot key', { exact: true }).selectOption('generated');
  await page.getByRole('button', { name: 'Create bot', exact: true }).click();
  await confirmPin(page);
  await expect(page.getByRole('heading', { name: 'Game Helper · Bot' })).toBeVisible();
  await page.getByRole('button', { name: 'Copy bot recovery key' }).click();
  expect(await page.evaluate(() => (window as unknown as { copied?: string }).copied)).toBeUndefined();
  await confirmPin(page);
  await expect.poll(() => page.evaluate(() => (window as unknown as { copied?: string }).copied)).toMatch(/^nsec1/);
  await helper.getByRole('button', { name: 'View bot contacts' }).click();
  await page.getByRole('button', { name: 'New contact', exact: true }).first().click();
  await page.getByLabel('Name', { exact: true }).fill('Bot-only friend');
  await page.getByRole('button', { name: 'Save contact' }).click();
  await expect(page.getByRole('button', { name: /Open Bot-only friend/ })).toBeVisible();
  await page.getByRole('button', { name: 'Back to bots' }).click();
  const game = page.locator('section.card').filter({ has: page.getByRole('heading', { name: 'Game Helper · Bot', exact: true }) });
  await game.getByRole('button', { name: 'View bot contacts' }).click();
  await expect(page.getByText('Bot-only friend', { exact: true })).toHaveCount(0);
  await navigateViaHarness(page, 'contacts');
  await expect(page.getByText('Bot-only friend', { exact: true })).toHaveCount(0);
  await navigateViaHarness(page, 'home');
  await expect(page.locator('.carousel-viewport')).toBeVisible();
  await navigateViaHarness(page, 'bots');
  await expect(page.getByRole('heading', { name: 'Helper · Bot', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Game Helper · Bot' })).toBeVisible();
  await navigateViaHarness(page, 'home');
  await expect(page.locator('.carousel-viewport')).toBeVisible();
  await page.keyboard.press('ArrowDown');
  await expect(page.locator('.nav-dots-v .nav-dot').nth(1)).toHaveClass(/active/);
  await expect(page.getByRole('heading', { name: 'Helper · Bot', exact: true })).toBeVisible();
  await page.keyboard.press('ArrowRight');
  await expect(page.locator('.nav-dots-h .nav-dot').nth(1)).toHaveClass(/active/);
  await page.keyboard.press('ArrowRight');
  await expect(page.locator('.nav-dots-h .nav-dot').nth(2)).toHaveClass(/active/);
  await page.getByRole('button', { name: 'View bot contacts' }).click();
  await expect(page.getByRole('button', { name: /Open Bot-only friend/ })).toBeVisible();
  await navigateViaHarness(page, 'home');
  await expect(page.locator('.carousel-viewport')).toBeVisible();
  await page.keyboard.press('ArrowRight');
  await expect(page.locator('.nav-dots-h .nav-dot').nth(3)).toHaveClass(/active/);
  await page.getByRole('button', { name: 'Hide bot from carousel' }).click();
  await expect(page.getByRole('heading', { name: 'Game Helper · Bot', exact: true })).toBeVisible();
  await navigateViaHarness(page, 'settings');
  await page.getByRole('button', { name: /Bots.*Keys and persona ownership/ }).click();
  await page.locator('section.card').filter({ has: page.getByRole('heading', { name: 'Helper · Bot', exact: true }) })
    .getByRole('button', { name: 'Show bot in carousel' }).click();
});
